server:
  port: 8085

spring:
  application:
    name: swi-api-gateway
  cloud:
    gateway:
      server:
        webflux:      
          routes:
          - id: swi-api-signing
            uri: http://localhost:8082
            predicates:
            - Path=/api/v1/**, /css/**           
